on:
  workflow_dispatch:

jobs:
  createserver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Template
        uses: actions/checkout@main

      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDS}}

      - name: Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 36094c3e-09a9-4d87-b2f6-8155155e2916
          resourceGroupName: rg-cloud-svathumalli
          template: ./template/webapp.json